name: output info
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: output github context in text
              run: echo "${{github}}"
            - name: output github context in JSON
              run: echo "${{toJSON(github)}}"